com::diag::amigo::LC100
NAME
com::diag::amigo::LC100 -
This is the derived (sub) class for the LC100 software that contains the actual data structures whose sizes depend on the actual size of the display.
SYNOPSIS
#include <LC100.h>
Inherits com::diag::amigo::LC100Base.
Public Types
enum Ascii
Public Member Functions
LC100 (Display &display, boolean sample=false, boolean debug=false, int ms=0)
virtual ~LC100 ()
void begin ()
void setCursor (byte col, byte row)
void home ()
void down ()
void up ()
void erase (byte colFrom, byte rowFrom, byte colTo, byte rowTo)
void clear ()
int read (char *buffer)
size_t write (uint8_t ch)
Public Attributes
const byte COLS
const byte ROWS
Protected Types
enum Constant
enum State
enum Action
Protected Member Functions
byte index (byte col, byte row)
byte index (byte row)
size_t emit (uint8_t ch)
size_t frame (uint8_t ch)
byte one (byte value)
Detailed Description
template<byte _COLS_, byte _ROWS_> class com::diag::amigo::LC100< _COLS_, _ROWS_ >
This is the derived (sub) class for the LC100 software that contains the actual data structures whose sizes depend on the actual size of the display.
It is templatized so that the display dimensions can be passed as arguments at compile time.
Definition at line 368 of file LC100.h.
Member Enumeration Documentation
enum com::diag::amigo::LC100Base::Action [protected, inherited]
Actions which the push down automaton may execute. CONSUMED is the default action. All of the enumerated values are printable, making it easy to trace the PDA as it executes.
Definition at line 124 of file LC100.h.
enum com::diag::amigo::LC100Base::State [protected, inherited]
States in which the push down automaton may be. DATA is the start state. There is no end state. All of the enumerated values are printable, making it easy to trace the PDA as it executes.
Definition at line 109 of file LC100.h.
Constructor & Destructor Documentation
template<byte _COLS_, byte _ROWS_> com::diag::amigo::LC100< _COLS_, _ROWS_ >::LC100 (Display & display, boolean sample = false, boolean debug = false, int ms = 0) [inline]
Ctor. Parameters:
display refers to the object that implements the Display interface.
sample if true causes the joystick value to be returned continuously as long as a button is pressed; if false, the joystick value is returned intermittently when the button is released.
debug enables debug output if debugging was compiled in.
ms is the number of milliseconds to delay between each individual update of the display, which can make debugging a lot easier.
Definition at line 390 of file LC100.h.
Member Function Documentation
void com::diag::amigo::LC100Base::begin () [inherited]
Initialize this object. This only needs to be called once.
Definition at line 724 of file LC100.cpp.
References com::diag::amigo::Display::begin(), com::diag::amigo::LC100Base::clear(), com::diag::amigo::LC100Base::COLS, and com::diag::amigo::LC100Base::ROWS.
void com::diag::amigo::LC100Base::down () [inherited]
Scroll the scroll area down, leaving the cursor placed at a blank line at the top of the scroll area. By default, the scroll area is the entire display.
Definition at line 176 of file LC100.cpp.
References com::diag::amigo::Display::clear(), com::diag::amigo::LC100Base::index(), com::diag::amigo::LC100Base::ROWS, com::diag::amigo::LC100Base::setCursor(), com::diag::amigo::Display::setCursor(), and com::diag::amigo::Display::write().
Referenced by com::diag::amigo::LC100Base::write().
size_t com::diag::amigo::LC100Base::emit (uint8_t ch) [protected, inherited]
Emit a character, which both displays it on the actual display and stores it appropriately in the frame buffer. The returned value is the number of characters processed, which is nominally one but may be zero if the character is somehow invalid or negative if an error occurred.
Parameters:
ch is the character to be emitted.
Returns:
the number of characters emitted.
Definition at line 69 of file LC100.cpp.
References com::diag::amigo::LC100Base::COLS, com::diag::amigo::LC100Base::index(), com::diag::amigo::LC100Base::ROWS, and com::diag::amigo::Display::write().
Referenced by com::diag::amigo::LC100Base::erase(), com::diag::amigo::LC100Base::frame(), and com::diag::amigo::LC100Base::write().
void com::diag::amigo::LC100Base::erase (byte colFrom, byte rowFrom, byte colTo, byte rowTo) [inherited]
Erase a square bordered by the specified upper left and lower right corners inclusive. Erasing is done by writing blanks into the display left to right, top to bottom. The cursor is placed back in its original position.
Parameters:
colFrom is the zero-based column of the upper left corner of the erased square.
rowFrom is the zero-based row of the upper left corner of the erased square.
colTo is the zero-based column of the lower right corner of the erased square.
rowTo is the zero-based row of the lower right corner of the erased square.
Definition at line 109 of file LC100.cpp.
References com::diag::amigo::LC100Base::COLS, com::diag::amigo::LC100Base::emit(), com::diag::amigo::LC100Base::index(), com::diag::amigo::LC100Base::ROWS, and com::diag::amigo::LC100Base::setCursor().
Referenced by com::diag::amigo::LC100Base::frame(), and com::diag::amigo::LC100Base::write().
size_t com::diag::amigo::LC100Base::frame (uint8_t ch) [protected, inherited]
Frame a character appropriately by dealing with line wrapping (if enabled) and screen scrolling (ditto). Parameters:
ch is the character to be framed.
Returns:
the number of characters framed.
Definition at line 144 of file LC100.cpp.
References com::diag::amigo::LC100Base::COLS, com::diag::amigo::LC100Base::emit(), com::diag::amigo::LC100Base::erase(), com::diag::amigo::LC100Base::index(), com::diag::amigo::LC100Base::ROWS, com::diag::amigo::LC100Base::setCursor(), and com::diag::amigo::LC100Base::up().
Referenced by com::diag::amigo::LC100Base::write().
byte com::diag::amigo::LC100Base::index (byte row) [protected, inherited]
Concert a zero-based row value into an array index. Parameters:
row is the zero-based row value.
Returns:
an array index.
Definition at line 35 of file LC100.cpp.
References com::diag::amigo::LC100Base::ROWS.
byte com::diag::amigo::LC100Base::index (byte col, byte row) [protected, inherited]
Convert a zero-based column and row coordinate into a frame buffer index. Parameters:
col is the zero-based column value.
row is the zero-based row value.
Returns:
a frame buffer index.
Definition at line 39 of file LC100.cpp.
References com::diag::amigo::LC100Base::COLS.
Referenced by com::diag::amigo::LC100Base::down(), com::diag::amigo::LC100Base::emit(), com::diag::amigo::LC100Base::erase(), com::diag::amigo::LC100Base::frame(), com::diag::amigo::LC100Base::up(), and com::diag::amigo::LC100Base::write().
byte com::diag::amigo::LC100Base::one (byte value) [protected, inherited]
Convert a one-based column or row value into a zero-based column or row value. Parameters:
value is the one-based value.
Returns:
the zero-based value.
Definition at line 43 of file LC100.cpp.
Referenced by com::diag::amigo::LC100Base::write().
int com::diag::amigo::LC100Base::read (char * buffer) [inherited]
Read the current joy stick stimulus into a buffer of at least four bytes in length. If the joy stick is indicating movement, the buffer will contain a VT100 (ANSI) arrow escape sequence indicating the direction of movement. The buffer will be nul-terminated, allowing it to be written directly to the serial port. Return the number of bytes placed into the buffer, zero indicating that there is no joy stick stimulus at this time.
Parameters:
buffer points to a buffer of at least four bytes in length.
Returns:
the number of bytes placed in the buffer.
Definition at line 667 of file LC100.cpp.
References com::diag::amigo::Display::read().
void com::diag::amigo::LC100Base::setCursor (byte col, byte row) [inherited]
Place the cursor at the specified position. The column and row coordinates are taken modulo of the actual display dimensions.
Parameters:
col is the zero-based column number.
row is the zero-based row number.
Definition at line 51 of file LC100.cpp.
References com::diag::amigo::LC100Base::COLS, com::diag::amigo::LC100Base::ROWS, and com::diag::amigo::Display::setCursor().
Referenced by com::diag::amigo::LC100Base::clear(), com::diag::amigo::LC100Base::down(), com::diag::amigo::LC100Base::erase(), com::diag::amigo::LC100Base::frame(), com::diag::amigo::LC100Base::up(), and com::diag::amigo::LC100Base::write().
void com::diag::amigo::LC100Base::up () [inherited]
Scroll the scroll area up, leaving the cursor placed at a blank line at the bottom of the scroll area. By default, the scroll area is the entire display.
Definition at line 197 of file LC100.cpp.
References com::diag::amigo::Display::clear(), com::diag::amigo::LC100Base::index(), com::diag::amigo::LC100Base::ROWS, com::diag::amigo::LC100Base::setCursor(), com::diag::amigo::Display::setCursor(), and com::diag::amigo::Display::write().
Referenced by com::diag::amigo::LC100Base::frame(), and com::diag::amigo::LC100Base::write().
size_t com::diag::amigo::LC100Base::write (uint8_t ch) [inherited]
Write the current character to the display. This character may be part of a VT100 (ANSI) escape sequence, in which case it is not actually written to the display, but will be executed once the complete escape sequence is captured.
Parameters:
ch is the character to be written to the display.
Returns:
the number of characters processed, which could be zero if the character is somehow invalid in the context of the current escape sequence, or negative is an error occurred.
Definition at line 246 of file LC100.cpp.
References com::diag::amigo::LC100Base::clear(), com::diag::amigo::LC100Base::COLS, com::diag::amigo::LC100Base::down(), com::diag::amigo::LC100Base::emit(), com::diag::amigo::LC100Base::erase(), com::diag::amigo::LC100Base::frame(), com::diag::amigo::Display::home(), com::diag::amigo::LC100Base::index(), com::diag::amigo::LC100Base::one(), com::diag::amigo::LC100Base::ROWS, com::diag::amigo::LC100Base::setCursor(), and com::diag::amigo::LC100Base::up().
Author
Generated automatically by Doxygen for Amigo from the source code.