com::diag::amigo::Display
NAME
com::diag::amigo::Display -
This pure (abstract) class defines the interface that the LC100 software expects to be implemented by any display that it uses.
SYNOPSIS
#include <LC100.h>
Inherited by Mock.
Public Types
enum Read
Public Member Functions
virtual void begin (byte cols, byte rows)=0
virtual void home ()=0
virtual void clear ()=0
virtual void setCursor (byte col, byte row)=0
virtual size_t write (uint8_t ch)=0
virtual Read read ()=0
Detailed Description
This pure (abstract) class defines the interface that the LC100 software expects to be implemented by any display that it uses.
Definition at line 24 of file LC100.h.
Member Function Documentation
virtual void com::diag::amigo::Display::begin (byte cols, byte rows) [pure virtual]
Initialize. This needs to be done only once.
Parameters:
cols is the number of columns in this display.
rows is the number of rows in this display.
Implemented in Mock.
Referenced by com::diag::amigo::LC100Base::begin().
virtual Read com::diag::amigo::Display::read () [pure virtual]
Read the joystick. The returned value will be an enumerated value indicating movement left, down, up, or right, a select indication, or no input.
Returns:
an enumerated value.
Implemented in Mock.
Referenced by com::diag::amigo::LC100Base::read().
virtual void com::diag::amigo::Display::setCursor (byte col, byte row) [pure virtual]
Place the cursor at the specified position. The column and row coordinates are taken modulo of the actual display dimensions.
Parameters:
col is the zero-based column number.
row is the zero-based row number.
Implemented in Mock.
Referenced by com::diag::amigo::LC100Base::down(), com::diag::amigo::LC100Base::setCursor(), and com::diag::amigo::LC100Base::up().
virtual size_t com::diag::amigo::Display::write (uint8_t ch) [pure virtual]
Write a character to the display. The signed value that is returned will typically be one, but can be zero if the specified character was somehow invalid, or negative if an error writing the character occurred.
Parameters:
ch is the character that is written to the display.
Returns:
the number of characters written.
Implemented in Mock.
Referenced by com::diag::amigo::LC100Base::down(), com::diag::amigo::LC100Base::emit(), and com::diag::amigo::LC100Base::up().
Author
Generated automatically by Doxygen for Amigo from the source code.