.TH "LC100.cpp" 3 "21 Feb 2012" "Version 0.2.0" "Amigo" \" -*- nroff -*-
.ad l
.nh
.SH NAME
LC100.cpp \- 
.PP
Copyright 2012 Digital Aggregates Corporation, Colorado, USA
.br
 Licensed under the terms in \fBREADME.h\fP
.br
 Chip Overclock mailto:coverclock@diag.com
.br
 http://www.diag.com/navigation/downloads/Amigo.html
.br
.  

.SH SYNOPSIS
.br
.PP
\fC#include 'LC100.h'\fP
.br
\fC#include <Arduino.h>\fP
.br
\fC#include <Print.h>\fP
.br
\fC#include <stdint.h>\fP
.br
\fC#include <string.h>\fP
.br

.SH "Detailed Description"
.PP 
Copyright 2012 Digital Aggregates Corporation, Colorado, USA
.br
 Licensed under the terms in \fBREADME.h\fP
.br
 Chip Overclock mailto:coverclock@diag.com
.br
 http://www.diag.com/navigation/downloads/Amigo.html
.br
. 


.PP
Definition in file \fBLC100.cpp\fP.
.SH "Author"
.PP 
Generated automatically by Doxygen for Amigo from the source code.
