.TH "README.h" 3 "21 Feb 2012" "Version 0.2.0" "Amigo" \" -*- nroff -*-
.ad l
.nh
.SH NAME
README.h \- 
.PP
This is the README for this project.  

.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 
This is the README for this project. 


.PP
Definition in file \fBREADME.h\fP.
.SH "Author"
.PP 
Generated automatically by Doxygen for Amigo from the source code.
